Repository quintel/etmodel, pull requests merged in 2021-01, with the labels that each got.

#3528 Removed outdated embedded youtube videos
  config/locales/interface/input_elements/en_supply_electricity.yml
  config/locales/interface/input_elements/nl_demand_buildings.yml
  config/locales/interface/input_elements/nl_supply_electricity.yml
  config/locales/interface/input_elements/nl_supply_transport.yml
Labels: Clean up

#3529 Removed outdated household hot water files
  config/interface/output_element_series/source_of_hot_water_in_households.yml
  config/interface/output_elements/demand_households.yml
  config/locales/interface/output_elements/en_demand.yml
  config/locales/interface/output_elements/nl_demand.yml
Labels: Clean up

#3543 Updated biomass labels in sankeys to include greengas
  app/assets/javascripts/d3/sankey.coffee
  config/locales/interface/input_elements/en_supply_biomass.yml
  config/locales/interface/input_elements/en_supply_electricity.yml
  config/locales/interface/input_elements/nl_costs.yml
  config/locales/interface/input_elements/nl_demand_transport.yml
  config/locales/interface/input_elements/nl_supply_biomass.yml
  config/locales/interface/input_elements/nl_supply_ccus.yml
  config/locales/interface/input_elements/nl_supply_electricity.yml
  config/locales/interface/output_element_series/nl_labels.yml
  config/locales/interface/output_elements/en_supply.yml
  config/locales/interface/output_elements/labels_groups/en_labels.yml
  config/locales/interface/output_elements/labels_groups/nl_labels.yml
  config/locales/interface/output_elements/nl_cost.yml
  config/locales/interface/output_elements/nl_supply.yml
  config/locales/interface/slides/nl_flexibility.yml
  config/locales/interface/slides/nl_supply.yml
  config/reports/main.nl.liquid
Labels: Charts

#3547 Changed descriptions of electricity storage sliders to exclude hard-coded data
  config/interface/input_elements/flexibility_flexibility_power_storage.yml
  config/locales/interface/input_elements/en_flexibility.yml
  config/locales/interface/input_elements/nl_flexibility.yml
  config/nodes_download_source.yml
Labels: Clean up

#3545 Mondaine drive and ESDLSuite connection
  Gemfile
  Gemfile.lock
  app/assets/javascripts/esdl.js
  app/assets/stylesheets/_scenarios.sass
  app/assets/stylesheets/esdl.sass
  app/controllers/esdl_suite_controller.rb
  app/controllers/import_esdl_controller.rb
  app/models/esdl_suite_id.rb
  app/models/user.rb
  app/services/browse_esdl_suite.rb
  app/services/create_esdl_scenario.rb
  app/services/esdl_suite_service.rb
  app/services/fetch_from_esdl_suite.rb
  app/views/import_esdl/_browse.html.haml
  app/views/import_esdl/index.html.haml
  config/config.sample.yml
  config/locales/en_esdl.yml
  config/locales/nl_esdl.yml
  config/routes.rb
  db/migrate/20201217090701_create_esdl_suite_id.rb
  db/schema.rb
  spec/controllers/esdl_suite_controller_spec.rb
  spec/models/esdl_suite_id_spec.rb
  spec/services/browse_esdl_suite_spec.rb
  spec/services/esdl_suite_service_spec.rb
  spec/services/fetch_from_esdl_suite_spec.rb
  spec/support/esdl_suite_helper.rb
  spec/support/services_helper.rb
Labels: mondaine
